/*
 * Esta classe cria a tabela para impressão de uma matriz
 * O objeto da classe é criado pela classe UserInterface
 * O conteúdo da tabela é alterado pela troca de modelo
 */

package app.frontend;

/**
 *
 * @author André de Sousa
 */
public class MatrixTableResults extends javax.swing.JPanel {

    /**
     * Creates new form ResultsTables
     */
    public MatrixTableResults() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResults = new javax.swing.JTable();

        jTableResults.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {}, new String[] {}));
        jTableResults.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableResults.setGridColor(new java.awt.Color(222, 222, 222));
        jTableResults.setRowHeight(20);
        jTableResults.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableResults);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    } // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableResults;
    // End of variables declaration//GEN-END:variables
}
